### ISSUE TITLE
[BUG] nvt.ops.Normalize() and nvt.ops.NormalizeMinMax() do not work with latest Merlin Docker image

### ISSUE THREAD

**Issue by IamGianluca** [NVIDIA-Merlin/NVTabular#1407]
**Describe the bug**
NVTabular return the following error when using `nvt.ops.Normalize()` or `nvt.ops.NormalizeMinMax()`.

```---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in add_ptx(self, ptx, name)
   2159         try:
-> 2160             driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
   2161                                  ptxbuf, len(ptx), namebuf, 0, None, None)

/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    299             retcode = libfn(*args)
--> 300             self._check_error(fname, retcode)
    301         return safe_cuda_api_call

/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    334                     raise CudaDriverError("CUDA initialized before forking")
--> 335             raise CudaAPIError(retcode, msg)
    336 

CudaAPIError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

LinkerError                               Traceback (most recent call last)
/tmp/ipykernel_3623737/2656170959.py in <module>
      2 workflow = nvt.Workflow(cont_features)
      3 dataset = nvt.Dataset(t)
----> 4 workflow.fit(dataset)
      5 # apply the preprocessing workflow in the dataset and converts the resulting Dask cudf dataframe to a cudf dataframe
      6 out = workflow.transform(dataset).compute()

/nvtabular/nvtabular/workflow/workflow.py in fit(self, dataset)
    209 
    210             for computed_stats, op in zip(results, ops):
--> 211                 op.fit_finalize(computed_stats)
    212 
    213             # Remove all the operators we processed in this phase, and remove

/opt/conda/lib/python3.8/contextlib.py in inner(*args, **kwds)
     73         def inner(*args, **kwds):
     74             with self._recreate_cm():
---> 75                 return func(*args, **kwds)
     76         return inner
     77 

/nvtabular/nvtabular/ops/normalize.py in fit_finalize(self, dask_stats)
    156         cols = index.values_host if hasattr(index, "values_host") else index.values
    157         for col in cols:
--> 158             self.mins[col] = dask_stats["mins"][col]
    159             self.maxs[col] = dask_stats["maxs"][col]
    160 

/opt/conda/lib/python3.8/site-packages/cudf/core/series.py in __getitem__(self, arg)
   1159             return self.iloc[arg]
   1160         else:
-> 1161             return self.loc[arg]
   1162 
   1163     iteritems = SingleColumnFrame.__iter__

/opt/conda/lib/python3.8/site-packages/cudf/core/series.py in __getitem__(self, arg)
    177             return result
    178         try:
--> 179             arg = self._loc_to_iloc(arg)
    180         except (TypeError, KeyError, IndexError, ValueError):
    181             raise KeyError(arg)

/opt/conda/lib/python3.8/site-packages/cudf/core/series.py in _loc_to_iloc(self, arg)
    215                     return found_index
    216             try:
--> 217                 found_index = self._frame.index._values.find_first_value(
    218                     arg, closest=False
    219                 )

/opt/conda/lib/python3.8/site-packages/cudf/core/column/string.py in find_first_value(self, value, closest)
   5578         self, value: ScalarLike, closest: bool = False
   5579     ) -> int:
-> 5580         return self._find_first_and_last(value)[0]
   5581 
   5582     def find_last_value(self, value: ScalarLike, closest: bool = False) -> int:

/opt/conda/lib/python3.8/site-packages/cudf/core/column/string.py in _find_first_and_last(self, value)
   5571         )
   5572         found_indices = libcudf.unary.cast(found_indices, dtype=np.int32)
-> 5573         first = column.as_column(found_indices).find_first_value(np.int32(1))
   5574         last = column.as_column(found_indices).find_last_value(np.int32(1))
   5575         return first, last

/opt/conda/lib/python3.8/site-packages/cudf/core/column/numerical.py in find_first_value(self, value, closest)
    458             elif value > self.max():
    459                 return len(self)
--> 460         return self._find_value(value, closest, cudautils.find_first, "gt")
    461 
    462     def find_last_value(self, value: ScalarLike, closest: bool = False) -> int:

/opt/conda/lib/python3.8/site-packages/cudf/core/column/numerical.py in _find_value(self, value, closest, find, compare)
    430         found = 0
    431         if len(self):
--> 432             found = find(self.data_array_view, value, mask=self.mask,)
    433         if found == -1:
    434             if self.is_monotonic_increasing and closest:

/opt/conda/lib/python3.8/site-packages/cudf/utils/cudautils.py in find_first(arr, val, mask, compare)
    132     """
    133 
--> 134     found_col = find_index_of_val(arr, val, mask=mask, compare=compare)
    135     found_col = found_col.find_and_replace([arr.size], [None], True)
    136 

/opt/conda/lib/python3.8/site-packages/cudf/utils/cudautils.py in find_index_of_val(arr, val, mask, compare)
    111                 )
    112             else:
--> 113                 gpu_mark_found_int.forall(found.size)(
    114                     arr, val, found, arr.size
    115                 )

/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py in __call__(self, *args)
    359             kernel = self.kernel
    360         else:
--> 361             kernel = self.kernel.specialize(*args)
    362         blockdim = self._compute_thread_per_block(kernel)
    363         griddim = (self.ntasks + blockdim - 1) // blockdim

/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py in specialize(self, *args)
   1019         targetoptions = self.targetoptions
   1020         targetoptions['link'] = self.link
-> 1021         specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
   1022                                     targetoptions)
   1023         self.specializations[cc, argtypes] = specialization

/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py in __init__(self, py_func, sigs, targetoptions)
    897             if len(sigs) > 1:
    898                 raise TypeError("Only one signature supported at present")
--> 899             self.compile(sigs[0])
    900             self._can_compile = False
    901 

/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py in compile(self, sig)
   1100             self.overloads[argtypes] = kernel
   1101 
-> 1102             kernel.bind()
   1103             self.sigs.append(sig)
   1104         return kernel

/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py in bind(self)
    588         Force binding to current CUDA context
    589         """
--> 590         self._func.get()
    591 
    592     @property

/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py in get(self)
    439             # Link
    440             linker = driver.Linker(max_registers=self.max_registers)
--> 441             linker.add_ptx(ptx)
    442             for path in self.linking:
    443                 linker.add_file_guess_ext(path)

/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in add_ptx(self, ptx, name)
   2161                                  ptxbuf, len(ptx), namebuf, 0, None, None)
   2162         except CudaAPIError as e:
-> 2163             raise LinkerError("%s\n%s" % (e, self.error_log))
   2164 
   2165     def add_file(self, path, kind):

LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.4'


```

**Steps/Code to reproduce bug**

```python
t = cudf.DataFrame({"numbers": [1,2,3,4,5]})
cont_features = ['numbers'] >> nvt.ops.Normalize()
workflow = nvt.Workflow(cont_features)
dataset = nvt.Dataset(t)
workflow.fit(dataset)
out = workflow.transform(dataset).compute()
```

**Expected behavior**
It should return the normalized `numbers` feature.

**Environment details (please complete the following information):**

 - Environment location: Nvidia Merlin Docker image (`nvcr.io/nvidia/merlin/merlin-pytorch-training:22.02`) 
 - Method of NVTabular install: Pre-installed with Merlin Docker image
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used: Dockerfile used pasted below.
 
```
FROM nvcr.io/nvidia/merlin/merlin-pytorch-training:22.02
```

**Comment by rnyak** [comment]
@IamGianluca  I ran your  sample code in  `nvcr.io/nvidia/merlin/merlin-pytorch-training:22.02` and also in a conda env, and I could not reproduce the error. It worked fine for me.   Please be sure you have the latest `main` branch. 

Can you  please  provide more details about your env? your GPU, driver version, cuda toolkit version etc.

**Comment by IamGianluca** [comment]
@rnyak Hi and thank you for trying to reproduce the error! My GPU is an RTX 3090. In the hosting OS I have Driver Version: 470.42.01 and:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
``` 

Whereas in the Docker container I have Driver Version: 470.42.01 and:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
```

Could be just that I need to update the driver and toolkit in the host OS?

**Comment by IamGianluca** [comment]
You're right! It solved the issue. I'll keep that in mind in the future. Thank you for your help!
