### ISSUE TITLE
[BUG] getting started `03-Training-with-TF` nb gives OOM on a 16 GB GPU

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/NVTabular#1518]
**Describe the bug**

I am getting OOM issue when I train `03-Training-with-TF` nb on a 16 GB GPU, and this can be problematic for users who are running these notebooks in the cloud with GPU memory sizes.

I can avoid OOM if I comment out `os.environ["TF_MEMORY_ALLOCATION"] = "0.7" ` line.  It works fine then. 

**Steps/Code to reproduce bug**

Run `03-Training-with-TF` to repro.

**Expected behavior**
Should run without OOM. I recommend to remove `os.environ["TF_MEMORY_ALLOCATION"] = "0.7" ` line from the example nb.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 
I am using `merlin-tensorflow-training:22.04`.

**Comment by rnyak** [comment]
@benfred what's your opinion? should we remove `out os.environ["TF_MEMORY_ALLOCATION"] = "0.7" line. It works fine without it. thanks.

**Comment by karlhigley** [comment]
Which example is this for? Let me see how it goes on an 11GB GPU. 😺

**Comment by rnyak** [comment]
> Which example is this for? Let me see how it goes on an 11GB GPU. 😺

This is for, getting-started-movielens [03-Training-with-TF.ipynb](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/03-Training-with-TF.ipynb). Thanks for testing it :)

**Comment by karlhigley** [comment]
Can confirm that this works better on an 11GB GPU without the `os.environ["TF_MEMORY_ALLOCATION"] = "0.7"` line 👍🏻

**Comment by EvenOldridge** [comment]
Default is to use `os.environ["TF_MEMORY_ALLOCATION"] = "0.5"`

This should be solved by https://github.com/NVIDIA-Merlin/Merlin/issues/229

**Comment by karlhigley** [comment]
@EvenOldridge https://github.com/NVIDIA-Merlin/Merlin/issues/229 is just an issue though—there's no actual code for that yet, right?

**Comment by EvenOldridge** [comment]
Closing as the merged PR above resolves this.
